name: Deploy functions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  format-checking:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run flake8 (with adjustments to allow for black's formatting)
      run: flake8 *.py --extend-ignore E203  --extend-ignore E722 --max-line-length 120
    
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run mypy
        run: |
          mypy *.py
        
  testing:
    runs-on: ubuntu-latest
    needs: [format-checking, type-checking]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Set environment variables
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run unit tests using pytest with coverage
      run: | 
        pytest --cov=. --cov-report=term --cov-fail-under=50

  deploy-functions:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Confirm Google Cloud Authentication
        run: gcloud auth list

      - name: Deploy api_create_tickets
        run: |
          gcloud functions deploy api_create_tickets \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_create_tickets \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_reserve_tickets
        run: |
          gcloud functions deploy api_reserve_tickets \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_reserve_tickets \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_release_held_tickets
        run: |
          gcloud functions deploy api_release_held_tickets \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_release_held_tickets \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_get_attendee_tickets
        run: |
          gcloud functions deploy api_get_attendee_tickets \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_get_attendee_tickets \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_purchase_tickets
        run: |
          gcloud functions deploy api_purchase_tickets \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_purchase_tickets \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest

      - name: Deploy api_redeem_ticket
        run: |
          gcloud functions deploy api_redeem_ticket \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --entry-point api_redeem_ticket \
          --set-secrets=SUPABASE_URL=projects/950999785047/secrets/SUPABASE_URL:latest \
          --set-secrets=SUPABASE_KEY=projects/950999785047/secrets/SUPABASE_KEY:latest